Revert "Add tests to ensure hardware only for RuntimeShader API"
Revert submission 16475336-RuntimeShader_softwareOnly

Reason for revert: Breaking tests as system is dying
Error: Software rendering doesn't support RuntimeShader
Bug: b/211066630

Reverted Changes:
Id0ee4d1f0:Enforce that RuntimeShader is only hardware accele...
Ib4c2e54bd:Add tests to ensure hardware only for RuntimeShade...

Change-Id: Iddb4319868253765e789aa0b39b034d2ff8891cb
(cherry picked from commit 6bcd595d485abcb2117de82ae4558757597279bf)
Merged-In:Iddb4319868253765e789aa0b39b034d2ff8891cb