Fix NearbyDevicesRenouncePermissionTest
This test was sometimes failing with:

    java.lang.NullPointerException: Attempt to invoke virtual method
    'void android.bluetooth.le.BluetoothLeScanner.startScan(android.
    bluetooth.le.ScanCallback)' on a null object reference

...which was traced back to bm.getAdapter().getBluetoothLeScanner()
returning null.  This only occurs when the BluetoothAdapter is OFF.

So, add code to enable the Bluetooth adapter before the test runs, and
when the test ends, put it back in its original state.

Bug: 192898018
Test: atest NearbyDevicesRenouncePermissionTest
Change-Id: I6d90f5f0f5b63d7168d3a6c9f7b56f1bfbc68d0f

Change-Id: I74f084c7c3c57d6dca2ff488517c38351b43ef6f