Fix some flaky tests in CtsContentCaptureServiceTestCases module.
After calling enableService in the test case, it will trigger the
below flow continuously in a short time.

bind -> unbind -> unbind -> bind service

Although the service will be bound twice, it will be only triggered once
in normal case. But the service may be really bound twice due to timing,
then it will cause test case fail due to ServiceWatcher has been cleared
at last unbinding.

Exception:
java.lang.IllegalStateException: onConnected() without a watcher

To fix this condition, it would be better to clear ServiceWatcher after
finishing test case.

Bug: 140320065
Test: atest CtsContentCaptureServiceTestCases
Change-Id: I8f1898704f9c85a7f10821b90998cd362f6d20a8