Debug output improvements for SystemClockSntpTest
SystemClockSntpTest is failing in some environments with

"expected:<[false]> but was:<[]>" at SystemClockSntpTest.java:124.

There may be something being output on stderr that is not reported. This
change may reveal more information.

Minor refactoring here to remove a field while making changes to how
shell commands are executed. Also updates to the build target name to be
more standard while I add the dependency to a shared test module.

Bug: 251726675
Test: atest tests/tests/os/src/android/os/cts/SystemClockSntpTest.java
Change-Id: I7764cb738ea1f23d7e438a01467e76dfa58a7326