Fix com.google.android.gts.devicepolicy.DeviceOwnerTest#testDevicePolicyManager failure on automotive devices.
The call to Context.getUser() was throwing a NoSuchMethodError exception because ContextWrapper overrides that method without marking it as @TestApi.
Changed mUser as String and added try/catch to avoid FATAL error.
Removed final keyword to avoid compile error.

Bug: 219868141
Test: atest -b -t com.google.android.gts.devicepolicy.DeviceOwnerTest#testDevicePolicyManager
Change-Id: I3371649a73bf075c2164aed0d76ec5ffe4014fac